### ISSUE TITLE
css3动画-1s内左右摇动三次

### ISSUE THREAD

**Issue by fengcaian** [fengcaian/NOTES#58]
```css
.div{
	display:block;
	margin:50px auto;
}
.div:hover{
	animation:move 1s 0s 1;
	-webkit-animation:move 1s 0s 1;
	transform-origin:bottom;
	-webkit-transform-origin:bottom;
}

@keyframes move{
	0%{ 
	  -webkit-transform:rotate(0deg);
	  transform:rotate(0deg);
	}
	14.28% {  
	  -webkit-transform:rotate(6deg);
	  transform:rotate(6deg);
	}
	28.57% {  
	  -webkit-transform:rotate(-6deg);
	  transform:rotate(-6deg);
	}
	42.85% {  
	  -webkit-transform:rotate(4deg);
	  transform:rotate(4deg);
	}
	57.13% {  
	  -webkit-transform:rotate(-4deg);
	  transform:rotate(-4deg);
	}
	71.41% {  
	  -webkit-transform:rotate(2deg);
	  transform:rotate(2deg);
	}
	85.69% {  
	  -webkit-transform:rotate(-2deg);
	  transform:rotate(-2deg);
	}
	100% {  
	  -webkit-transform:rotate(0deg);
	  transform:rotate(0deg);
	}
}

@-webkit-keyframes move{
	0%{ 
	  -webkit-transform:rotate(0deg);
	  transform:rotate(0deg);
	}
	14.28% {  
	  -webkit-transform:rotate(6deg);
	  transform:rotate(6deg);
	}
	28.57% {  
	  -webkit-transform:rotate(-6deg);
	  transform:rotate(-6deg);
	}
	42.85% {  
	  -webkit-transform:rotate(4deg);
	  transform:rotate(4deg);
	}
	57.13% {  
	  -webkit-transform:rotate(-4deg);
	  transform:rotate(-4deg);
	}
	71.41% {  
	  -webkit-transform:rotate(2deg);
	  transform:rotate(2deg);
	}
	85.69% {  
	  -webkit-transform:rotate(-2deg);
	  transform:rotate(-2deg);
	}
	100% {  
	  -webkit-transform:rotate(0deg);
	  transform:rotate(0deg);
	}
}
```
鼠标移入后左右摇动三次
